name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
  release:
    types: [published, edited]
  pull_request:
    branches:
      - 'master'

env:
  GOFLAGS: -mod=readonly

jobs:
  build_libwekan:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49

      - name: Unit Tests
        run: go test ./... -v -tags integration

